name: Build master

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'exam.md'
    branches:
      - 'master'

env:
  OPAMROOT: /home/user/.opam
  OPAMYES: true

jobs:
  build:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    container:
      image: kakadu18/ocaml:sirius2023
      #options: --user user
      #options: -v /__w/test-ocaml-ci-docker/test-ocaml-ci-docker:/home/user/:rw -w /home/user/

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: sudo apt install python3.11-venv --yes
      - run: |
          python3 -m venv venv
          source venv/bin/activate && pip3 install cram

      - name: Test exprissions
        run: |
          source venv/bin/activate && opam exec -- cram ./expr.t

      - name: Test expressions
        run: |
          source venv/bin/activate && opam exec -- cram ./loops.t

      - name: Test expressions
        run: |
          source venv/bin/activate && opam exec -- cram ./funs.t


